logging:
    level:
#        tk.mybatis: DEBUG
        com.mvc.admin: DEBUG
spring:
    application:
        name: mvc-sms
    jackson:
        date-format: yyyy-MM-dd HH:mm:ss
        time-zone: GMT+8
        default-property-inclusion: non_null

server:
    port: 8653

eureka:
    instance:
        statusPageUrlPath: /info
        healthCheckUrlPath: /health
        # docker 部署开启
#        prefer-ip-address: true
#        ip-address: 127.0.0.1
    client:
        serviceUrl:
#            defaultZone: http://localhost:8761/eureka/
                    # docker 部署开启
            defaultZone: http://${EUREKA_HOST:localhost}:${EUREKA_PORT:8761}/eureka/

swagger:
    basepackage: com.mvc.user
    service:
        name: Admin Back
        description: Admin Back后端服务
        developer: 老A

#
#auth:
#  serviceId: mvc-auth
#  user:
#    token-header: Authorization
#  client:
#    id: mvc-user
#    secret: 123456
#    token-header: client-token

#redis-cache 相关
redis:
    pool:
         maxActive: 300
         maxIdle: 100
         maxWait: 1000
    host: localhost
    port: 6379
    password:
    timeout: 2000
    # 服务或应用名
    sysName: sms
    enable: true
    database: 0

yunpian.api.key: 0f937830e9c16699dc4d08b78aa8c5b3

spring.session.store-type: redis