spring:
    application:
        name: mvc-gate
    thymeleaf:
        mode: LEGACYHTML5
        cache: false
    jackson:
        date-format: yyyy-MM-dd HH:mm:ss
        time-zone: GMT+8
        default-property-inclusion: non_null
    redis:
        database: 1
        host: localhost
        pool:
            max-active: 20
    rabbitmq:
        host: localhost
        port: 5672
        username: admin
        password: admin
server:
    port: 8765 #启动端口
#
zuul:
  ignored-services: "*"
  sensitive-headers:
  prefix: /api #为zuul设置一个公共的前缀
  ratelimit: # 网关限流
    key-prefix: gate_rate
    enabled: true
    repository: REDIS #REDIS, JPA, IN_MEMORY
    behind-proxy: true
    default-policy: #optional - will apply unless specific policy exists
      limit: 200
      refresh-interval: 60 #default value (in seconds)
      type: #optional
        - user
        - origin
        - url

  routes:
    back:
      path: /user/**
      serviceId: mvc-user

    auth:
      path: /auth/**
      serviceId: mvc-auth

    sms:
      path: /message/**
      serviceId: mvc-sms

    user:
      path: /user/**
      serviceId: mvc-user

    console:
      path: /console/**
      serviceId: mvc-console

    admin-console:
      path: /ad-console/**
      serviceId: mvc-user-console

    admin:
      path: /admin/**
      serviceId: mvc-admin

    ethereum:
      path: /ethereum/**
      serviceId: mvc-etherenum

ribbon:
  eureka:
    enabled: true
  ReadTimeout: 60000
  ConnectTimeout: 60000
  MaxAutoRetries: 0
  MaxAutoRetriesNextServer: 1
  OkToRetryOnAllOperations: false


hystrix:
  threadpool:
    default:
      coreSize: 1000 ##并发执行的最大线程数，默认10
      maxQueueSize: 1000 ##BlockingQueue的最大队列数
      queueSizeRejectionThreshold: 500 ##即使maxQueueSize没有达到，达到queueSizeRejectionThreshold该值后，请求也会被拒绝
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 50000


gate:
  ignore:
    startWith: /static,/auth/client/validate,/message,/user/register,/user/login,/user/forget,/user/user/create,/user/user/token,/admin/user/token


auth:
  serviceId: mvc-auth
  user:
    token-header: Authorization
  client:
    token-header: client-token
    id: mvc-gate  #不填则默认读取spring.application.name
    secret: 123456